# Payroll Processing Intent Graph - Enhanced Schema Demo
# Tests all v0.1 schema features: centralized enums, strict validation, conditional rules

apiVersion: "intentive.dev/v1"
kind: "IntentGraph"
metadata:
  name: "payroll-processing"
  description: "Complete payroll processing workflow with approval gates, RBAC security, and rate limiting. Domain: Employee payroll with time records, tax calculations, deductions (health insurance, 401k, garnishments), approval workflows, ACH direct deposits, paystub generation, and compliance reporting."
  version: "1.0.0"
  labels:
    team: "hr"
    domain: "finance"

spec:
  config:
    concurrency:
      maxParallel: 2
    timeout: 300
    retry:
      maxAttempts: 2
      backoffMultiplier: 2

  nodes:
    - id: "authenticate_user"
      type: "action"
      properties:
        name: "Authenticate User"
        description: "Verify user identity and check authorization"
        handler: "auth.authenticate"
        timeout: 30
        
    - id: "check_approval_status"
      type: "decision"
      properties:
        name: "Check Approval Status"
        description: "Verify payroll run has proper approvals"
        handler: "approval.check_status"
        timeout: 15
    
    - id: "fetch_employee_data"
      type: "data"
      properties:
        name: "Fetch Employee Data"
        description: "Retrieve employee records from HR system"
        handler: "data.fetch_employees"
        timeout: 30
        retryCount: 2
    
    - id: "fetch_time_records"
      type: "data"
      properties:
        name: "Fetch Time Records"
        description: "Fetch time tracking data for pay period"
        handler: "data.fetch_time_records"
        timeout: 45
        retryCount: 1
    
    - id: "calculate_payroll"
      type: "action"
      properties:
        name: "Calculate Payroll"
        description: "Calculate gross pay, deductions, and net pay"
        handler: "payroll.calculate"
        timeout: 60
        criticalPath: true
    
    - id: "review_payroll"
      type: "decision"
      properties:
        name: "Review Payroll"
        description: "Manager review of calculated payroll"
        handler: "approval.review_payroll"
        timeout: 120
        requiresApproval: true
    
    - id: "generate_paystubs"
      type: "action"
      properties:
        name: "Generate Paystubs"
        description: "Generate individual paystub documents"
        handler: "documents.generate_paystubs"
        timeout: 90
        parallel: true
    
    - id: "submit_tax_filing"
      type: "action"
      properties:
        name: "Submit Tax Filing"
        description: "Submit tax withholding to authorities"
        handler: "tax.submit_filing"
        timeout: 45
        compliance: true
    
    - id: "process_payments"
      type: "action"
      properties:
        name: "Process Payments"
        description: "Execute ACH transfers and payment processing"
        handler: "payments.process"
        timeout: 90
        financial: true
    
    - id: "send_notifications"
      type: "action"
      properties:
        name: "Send Notifications"
        description: "Send payroll completion notifications"
        handler: "notifications.send"
        timeout: 15
        priority: "low"

  edges:
    - id: "auth_to_approval"
      from: "authenticate_user"
      to: "check_approval_status"
      type: "sequence"
      conditions: []
    
    - id: "approval_to_data"
      from: "check_approval_status"
      to: "fetch_employee_data"
      type: "conditional" 
      conditions:
        - field: "approval.status"
          operator: "equals"
          value: "approved"
    
    - id: "data_to_calc"
      from: "fetch_employee_data"
      to: "calculate_payroll"
      type: "sequence"
      conditions: []
    
    - id: "time_data_to_calc"
      from: "fetch_time_records"
      to: "calculate_payroll"
      type: "sequence"
      conditions: []
    
    - id: "calc_to_review"
      from: "calculate_payroll"
      to: "review_payroll"
      type: "sequence"
      conditions: []
    
    - id: "calc_to_payments"
      from: "calculate_payroll"
      to: "process_payments"
      type: "sequence"
      conditions: []
    
    # Payroll must be approved before downstream processes
    - id: "review_to_paystubs"
      from: "review_payroll"
      to: "generate_paystubs"
      type: "conditional"
      conditions:
        - field: "approval"
          operator: "equals"
          value: "approved"
    
    - id: "review_to_tax"
      from: "review_payroll"
      to: "submit_tax_filing"
      type: "conditional"
      conditions:
        - field: "approval"
          operator: "equals"
          value: "approved"
    
    - id: "review_to_deposits"
      from: "review_payroll"
      to: "process_payments"
      type: "conditional"
      conditions:
        - field: "approval"
          operator: "equals"
          value: "approved"
    
    # Notifications happen after everything else completes
    - id: "paystubs_to_notify"
      from: "generate_paystubs"
      to: "send_notifications"
      type: "sequence"
      conditions: []
    
    - id: "tax_to_notify"
      from: "submit_tax_filing"
      to: "send_notifications"
      type: "sequence"
      conditions: []
    
    - id: "deposits_to_notify"
      from: "process_payments"
      to: "send_notifications"
      type: "sequence"
      conditions: []

  guards:
    - name: "payroll_rbac_guard"
      type: "rbac"
      apply_to:
        nodes: ["authenticate_user"]
      config:
        type: "rbac"
        requiredRoles: ["payroll_admin", "finance_manager"]
        requiredPermissions: ["payroll:read", "payroll:write"]
        allowSuperuser: false
    
    - name: "payment_rate_limit_guard"
      type: "rate_limit"
      apply_to:
        nodes: ["process_payments"]
      config:
        type: "rate_limit"
        maxRequests: 3
        windowMs: 3600000
        keyGenerator: "user"
